name: linter

on: 
  push:
    branches:
    - main

jobs:
  golangci-running:
    name: "Golang CI running"
    runs-on: ubuntu-latest
    steps:
    
    - name: Клонирование текущего репозитория
      uses: actions/checkout@v3
    
    - name: Запуск golangci-lint
      uses: golangci/golangci-lint-action@v3.3.0
    
